### ISSUE TITLE
null pointer exception when creating @BigQueryType.toTable annotated case class

### ISSUE THREAD

**Issue by brammertottens** [spotify/scio-idea-plugin#186]
Hi, 

I'm using Intellij version 2021.2, and the IDEA plugin version 0.1.22, and I'm running into a null pointer exception when creating an annotated case class in order to store data in Big Query. I'm getting the following stack trace:

```
java.lang.NullPointerException
	at com.spotify.scio.BigQueryTypeInjector.injectFunctions(BigQueryTypeInjector.scala:78)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.SyntheticMembersInjector$.$anonfun$inject$1(SyntheticMembersInjector.scala:96)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.SyntheticMembersInjector$.$anonfun$inject$1$adapted(SyntheticMembersInjector.scala:95)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:920)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.SyntheticMembersInjector$.inject(SyntheticMembersInjector.scala:95)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.ScTypeDefinitionImpl.liftedTree3$1(ScTypeDefinitionImpl.scala:388)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.ScTypeDefinitionImpl.syntheticMethods(ScTypeDefinitionImpl.scala:387)
	at org.jetbrains.plugins.scala.lang.psi.api.toplevel.typedef.ScTemplateDefinition$SyntheticMembersExt$.membersWithSynthetic$extension(ScTemplateDefinition.scala:97)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.TermsCollector$.relevantMembers(SignatureProcessor.scala:203)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.TermsCollector.processScala(SignatureProcessor.scala:123)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.SignatureProcessor.processAll(SignatureProcessor.scala:44)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.SignatureProcessor.processAll$(SignatureProcessor.scala:39)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.TermsCollector.processAll(SignatureProcessor.scala:89)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.MixinNodes.$anonfun$build$1(MixinNodes.scala:50)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.MixinNodes.build(MixinNodes.scala:46)
	at org.jetbrains.plugins.scala.lang.psi.impl.ScalaPsiManager$SignatureCaches.cachedInUserData$1(ScalaPsiManager.scala:437)
	at org.jetbrains.plugins.scala.lang.psi.impl.ScalaPsiManager$SignatureCaches.cachedMap(ScalaPsiManager.scala:440)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.TypeDefinitionMembers$.$anonfun$getSignatures$1(TypeDefinitionMembers.scala:56)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.TypeDefinitionMembers$.ifValid(TypeDefinitionMembers.scala:78)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.TypeDefinitionMembers$.getSignatures(TypeDefinitionMembers.scala:56)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.TypeDefinitionMembers$.getSignatures(TypeDefinitionMembers.scala:65)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.TypeDefinitionMembers$.getSelfTypeSignatures(TypeDefinitionMembers.scala:112)
	at org.jetbrains.plugins.scala.lang.psi.ScalaPsiUtil$.superValsSignatures(ScalaPsiUtil.scala:578)
	at org.jetbrains.plugins.scala.annotator.OverridingAnnotator.checkOverrideClassParameters(OverridingAnnotator.scala:78)
	at org.jetbrains.plugins.scala.annotator.OverridingAnnotator.checkOverrideClassParameters$(OverridingAnnotator.scala:76)
	at org.jetbrains.plugins.scala.annotator.ScalaAnnotator.checkOverrideClassParameters(ScalaAnnotator.scala:48)
	at org.jetbrains.plugins.scala.annotator.ScalaAnnotator$$anon$1.visitClassParameter(ScalaAnnotator.scala:192)
	at org.jetbrains.plugins.scala.lang.psi.impl.statements.params.ScClassParameterImpl.acceptScala(ScClassParameterImpl.scala:75)
	at org.jetbrains.plugins.scala.lang.psi.api.ScalaPsiElement.accept(ScalaPsiElement.scala:108)
	at org.jetbrains.plugins.scala.lang.psi.api.ScalaPsiElement.accept$(ScalaPsiElement.scala:107)
	at org.jetbrains.plugins.scala.lang.psi.impl.ScalaStubBasedElementImpl.accept(ScalaPsiElementImpl.scala:72)
	at org.jetbrains.plugins.scala.annotator.ScalaAnnotator.annotate(ScalaAnnotator.scala:203)
	at org.jetbrains.plugins.scala.annotator.ScalaAnnotator.annotate(ScalaAnnotator.scala:56)
	at org.jetbrains.plugins.scala.codeInsight.daemon.ScalaAnnotatorHighlightVisitor.visit(ScalaAnnotatorHighlightVisitor.scala:37)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:335)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:268)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:294)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at org.jetbrains.plugins.scala.annotator.usageTracker.ScalaRefCountHolder.analyze(ScalaRefCountHolder.scala:81)
	at org.jetbrains.plugins.scala.codeInsight.daemon.ScalaAnnotatorHighlightVisitor.analyze(ScalaAnnotatorHighlightVisitor.scala:64)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:94)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:265)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:211)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:399)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:391)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:367)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:365)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by arlandism** [comment]
Same result for me

**Version**: 0.1.22
**Stacktrace**
```
java.lang.NullPointerException
	at com.spotify.scio.BigQueryTypeInjector.injectFunctions(BigQueryTypeInjector.scala:78)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.SyntheticMembersInjector$.$anonfun$inject$1(SyntheticMembersInjector.scala:96)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.SyntheticMembersInjector$.$anonfun$inject$1$adapted(SyntheticMembersInjector.scala:95)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.SyntheticMembersInjector$.inject(SyntheticMembersInjector.scala:95)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.ScTypeDefinitionImpl.liftedTree3$1(ScTypeDefinitionImpl.scala:388)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.ScTypeDefinitionImpl.syntheticMethods(ScTypeDefinitionImpl.scala:387)
	at org.jetbrains.plugins.scala.lang.psi.api.toplevel.typedef.ScTemplateDefinition$SyntheticMembersExt$.membersWithSynthetic$extension(ScTemplateDefinition.scala:99)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.TypesCollector$.processScala(SignatureProcessor.scala:117)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.SignatureProcessor.processAll(SignatureProcessor.scala:69)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.SignatureProcessor.processAll$(SignatureProcessor.scala:63)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.TypesCollector$.processAll(SignatureProcessor.scala:79)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.SignatureProcessor.processPsiClass(SignatureProcessor.scala:47)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.SignatureProcessor.processPsiClass$(SignatureProcessor.scala:46)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.TypesCollector$.processPsiClass(SignatureProcessor.scala:79)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.MixinNodes.$anonfun$build$1(MixinNodes.scala:56)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.MixinNodes.build(MixinNodes.scala:46)
	at org.jetbrains.plugins.scala.lang.psi.impl.ScalaPsiManager$SignatureCaches.cachedInUserData$1(ScalaPsiManager.scala:450)
	at org.jetbrains.plugins.scala.lang.psi.impl.ScalaPsiManager$SignatureCaches.cachedMap(ScalaPsiManager.scala:453)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.TypeDefinitionMembers$.$anonfun$getTypes$1(TypeDefinitionMembers.scala:64)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.TypeDefinitionMembers$.ifValid(TypeDefinitionMembers.scala:80)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.TypeDefinitionMembers$.getTypes(TypeDefinitionMembers.scala:64)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.TypeDefinitionMembers$.getTypes(TypeDefinitionMembers.scala:73)
	at org.jetbrains.plugins.scala.overrideImplement.ScalaOIUtil$.$anonfun$classMembersWithFilter$4(ScalaOIUtil.scala:142)
	at scala.Option.fold(Option.scala:263)
	at org.jetbrains.plugins.scala.overrideImplement.ScalaOIUtil$.classMembersWithFilter(ScalaOIUtil.scala:142)
	at org.jetbrains.plugins.scala.overrideImplement.ScalaOIUtil$.getMembersToImplement(ScalaOIUtil.scala:118)
	at org.jetbrains.plugins.scala.annotator.element.ScTemplateDefinitionAnnotator$.annotateNeedsToBeAbstract(ScTemplateDefinitionAnnotator.scala:230)
	at org.jetbrains.plugins.scala.annotator.element.ScTemplateDefinitionAnnotator$.annotate(ScTemplateDefinitionAnnotator.scala:33)
	at org.jetbrains.plugins.scala.annotator.element.ScTemplateDefinitionAnnotator$.annotate(ScTemplateDefinitionAnnotator.scala:23)
	at org.jetbrains.plugins.scala.annotator.element.ElementAnnotator.org$jetbrains$plugins$scala$annotator$element$ElementAnnotator$$doAnnotate(ElementAnnotator.scala:14)
	at org.jetbrains.plugins.scala.annotator.element.ElementAnnotator$.$anonfun$annotate$1(ElementAnnotator.scala:74)
	at org.jetbrains.plugins.scala.annotator.element.ElementAnnotator$.$anonfun$annotate$1$adapted(ElementAnnotator.scala:74)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.jetbrains.plugins.scala.annotator.element.ElementAnnotator$.annotate(ElementAnnotator.scala:74)
	at org.jetbrains.plugins.scala.annotator.ScalaAnnotator.annotate(ScalaAnnotator.scala:80)
	at org.jetbrains.plugins.scala.annotator.ScalaAnnotator.annotate(ScalaAnnotator.scala:54)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:131)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:108)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:343)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:276)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:302)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:305)
	at org.jetbrains.plugins.scala.annotator.usageTracker.ScalaRefCountHolder.analyze(ScalaRefCountHolder.scala:77)
	at org.jetbrains.plugins.scala.codeInsight.daemon.ScalaRefCountVisitor.analyze(ScalaRefCountVisitor.scala:48)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:305)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:273)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:218)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:419)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1152)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:412)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:411)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:387)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:213)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:385)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

```
